/*
 * Temperature Measurement API
 *
 * API for managing temperature measurement devices for multiple companies.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	ApiKey string `json:"apiKey,omitempty"`
}
