/*
 * Temperature Measurement API
 *
 * API for managing temperature measurement devices for multiple companies.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MeasurementsBody struct {

	DeviceId string `json:"deviceId,omitempty"`

	Temperature float64 `json:"temperature,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}
